### ISSUE TITLE
Example to set instanceOptions config

### ISSUE THREAD

**Issue by eriknyk** [mikew/browserify-brunch#3]
Hi, 

I want to pass the param -d to browserify plugin to generate the .map file and debug the my script
I tried 

`````
    plugins: {
        browserify: {
            extensions: 'js',
            instanceOptions: ['-d'],
            bundles: {
                'js/bundle.js': {
                    entry: './client.js'
                }
            }
        }
    }
`````
And it doesn't works,
I've tried too:

``
instanceOptions: ['d'],
instanceOptions: ['--debug'],
``
without luck,

Please help me,
Regards.

**Comment by mikew** [comment]
[The debug option should be set for you](https://github.com/mikew/browserify-brunch/blob/6f902a522f7f8689473e137ebeeed7ab9f262ed5/src/browserify-instance.coffee#L28), but it looks like browserify has changed since this plugin was written

the options passed to `instanceOptions` are not the command line arguments, [read about them here](https://github.com/substack/node-browserify#var-b--browserifyfiles-or-opts)

you're also setting them in the wrong place

```javascript
    plugins: {
        browserify: {
            extensions: 'js',
            bundles: {
                'js/bundle.js': {
                    entry: './client.js',
                    instanceOptions: { debug: true }
                }
            }
        }
    }
```

this is all in the readme
